BINARIES = sync_timer async_timer bind_args function_obj multithread

all:$(BINARIES)

include timer.mk

sync_timer:sync_timer.cc
async_timer:async_timer.cc
bind_args:bind_args.cc
function_obj:function_obj.cc
multithread:multithread.cc
