. common.sh
ROCM_DEVICE_LIBS_OUTPUT=$ROCM_OUTPUT/rocm-device-libs
CLANG_PATH=$ROCM_OUTPUT/llvm/lib/cmake/clang

mkdir -p $ROCM_DEVICE_LIBS_OUTPUT && cd $ROCM_DEVICE_LIBS_OUTPUT
cmake -DCMAKE_INSTALL_PREFIX=$ROCM_DEVICE_LIBS_OUTPUT -DCMAKE_BUILD_TYPE=$RELEASE_TYPE \
	-DCMAKE_PREFIX_PATH="$CLANG_PATH" \
	$ROCM_ROOT/ROCm-Device-Libs

make -j12
make install
