. ./common.sh
ROCM_LIBHSAKMT_OUTPUT=$ROCM_OUTPUT/libhsakmt

mkdir -p $ROCM_LIBHSAKMT_OUTPUT && cd $ROCM_LIBHSAKMT_OUTPUT

cmake -DCMAKE_INSTALL_PREFIX=$ROCM_LIBHSAKMT_OUTPUT -DCMAKE_BUILD_TYPE=$RELEASE_TYPE $ROCM_ROOT/ROCT-Thunk-Interface
make -j12
make install
