. common.sh
ROCM_ROCR_OUTPUT=$ROCM_OUTPUT/rocr-runtime
LIBHSAKMT_PATH=$ROCM_OUTPUT/libhsakmt/lib/cmake/hsakmt/
CLANG_PATH=$ROCM_OUTPUT/llvm/lib/cmake/clang

mkdir -p $ROCM_ROCR_OUTPUT && cd $ROCM_ROCR_OUTPUT
cmake -DIMAGE_SUPPORT=OFF -DCMAKE_INSTALL_PREFIX=$ROCM_ROCR_OUTPUT -DCMAKE_BUILD_TYPE=$RELEASE_TYPE \
	-DCMAKE_PREFIX_PATH="$LIBHSAKMT_PATH;$CLANG_PATH" \
	$ROCM_ROOT/ROCR-Runtime/src

make -j12
make install
